name: Get dependencies updates (new and unused versions)

on:
  workflow_dispatch:

jobs:
  js-checks:
    name: Get Javascript dependencies new and unused versions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jahia/jahia-modules-action/dependencies-get-unused-javascript@v2
        with:
          default_issue_assignee: 'rknj'
          github_token: ${{ secrets.GH_API_TOKEN }}
      - uses: jahia/jahia-modules-action/dependencies-get-new-versions-javascript@v2
        if: always()
        with:
          default_issue_assignee: 'rknj'
          github_token: ${{ secrets.GH_API_TOKEN }}

  java-checks:
    name: Get Java dependencies new and unused versions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jahia/jahia-modules-action/dependencies-get-unused-java@v2
        with:
          default_issue_assignee: 'rknj'
          github_token: ${{ secrets.GH_API_TOKEN }}
      - uses: jahia/jahia-modules-action/dependencies-get-new-versions-java@v2
        if: always()
        with:
          default_issue_assignee: 'rknj'
          github_token: ${{ secrets.GH_API_TOKEN }}
