name: Trigger Release creation

on:
  release:
    types: [prereleased]

jobs:
  handle_release:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger release publishing
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: curl -X POST --url 'https://circleci.com/api/v2/project/gh/${{ github.repository }}/pipeline'
          --header 'circle-token:${{ secrets.CIRCLECI_PIPELINE_LAUNCH_TOKEN }}'
          --header 'content-type:application/json'
          --data '{ "branch":"${{ github.event.release.target_commitish }}", "parameters":{ "run_pull_request":false, "target_branch":"${{ github.event.release.target_commitish }}",
          "release_version":"${{ github.event.release.tag_name }}", "is_release":true, "release_id":"${{ github.event.release.id }}",
          "github_repository":"${{ github.repository }}" } }'
